comment
npx firebase deploy

=== Deploying to 'tamakiii-awsome-project'...

i  deploying database, storage, firestore, functions, hosting
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint
/Users/tamakiii/Sites/tamakiii-sandbox/hello-firebase/functions
> tslint --project tsconfig.json

Running command: npm --prefix "$RESOURCE_DIR" run build

> functions@ build
/Users/tamakiii/Sites/tamakiii-sandbox/hello-firebase/functions
> tsc

src/index.ts:1:1 - error TS6133: 'functions' is declared but its value
is never read.

1 import * as functions from 'firebase-functions';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/index.ts:1:28 - error TS2307: Cannot find module
  'firebase-functions'.

  1 import * as functions from 'firebase-functions';
                               ~~~~~~~~~~~~~~~~~~~~